/**
 * Catálogo único de códigos de error del sistema.
 * Mantener sincronizado con auth.docs.js y responses.schema.js.
 */
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  AUTH_ERROR: 'AUTH_ERROR',

  LOGIN_ERROR: 'LOGIN_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  TOTP_SETUP_ERROR: 'TOTP_SETUP_ERROR',
  TOTP_VERIFY_ERROR: 'TOTP_VERIFY_ERROR',
  TOTP_LOGIN_ERROR: 'TOTP_LOGIN_ERROR',
  TOTP_SESSION_REQUIRED: 'TOTP_SESSION_REQUIRED',

  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  TOTP_ALREADY_CONFIGURED: 'TOTP_ALREADY_CONFIGURED',

  DATABASE_ERROR: 'DATABASE_ERROR',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
