version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: campusvote_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campusvote_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/sql:/database/sql
      - ./database/seeds:/database/seeds

volumes:
  db_data: