--src/database/sql/audit/001_enums.sql

BEGIN;

-- ENUM: TIPOS DE ACCIONES DE AUDITORÍA

DO $$
BEGIN
    CREATE TYPE audit_action_type AS ENUM (
        'LOGIN',
        'VERIFY_2FA',
        'CREATE_ELECTION',
        'OPEN_ELECTION',
        'CAST_VOTE',
        'CLOSE_ELECTION',
        'CERTIFY_RESULT',
        'PUBLISH_RESULT',
        'ASSIGN_JURY',
        'REVOKE_JURY',
        'DECLARE_JURY_CONFLICT',
        'CLEAR_JURY_CONFLICT',
        'REGENERATE_BALLOT',
        'REOPEN_RATING'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'ASSIGN_JURY';
ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'REVOKE_JURY';
ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'DECLARE_JURY_CONFLICT';
ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'CLEAR_JURY_CONFLICT';
ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'REGENERATE_BALLOT';
ALTER TYPE audit_action_type ADD VALUE IF NOT EXISTS 'REOPEN_RATING';

COMMIT;